"""
plots.py — Publication-Ready Figure Generator
ATRP Research | Jai Vidhyarthi | Synthara | 2026

WHY THIS FILE:
Research papers require visual evidence.
Reviewers expect at minimum 3 figures:
  Figure 1 — Protocol comparison (PDR, Reroute, Path Cost)
  Figure 2 — Lambda grid search curve
  Figure 3 — Weight sensitivity analysis

All data is read from results/ JSON files
generated by simulation.py and experiments.py.
We never hardcode numbers — figures always
reflect the latest simulation run.
"""

import json
import os
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

# ── Style Constants ─────────────────────────────────
BG       = '#0f172a'
SURFACE  = '#1e293b'
BORDER   = '#334155'
TEXT     = '#e2e8f0'
MUTED    = '#64748b'
SOFT     = '#94a3b8'

COLORS = {
    'atrp'    : '#3b82f6',
    'dijkstra': '#f59e0b',
    'aodv'    : '#8b5cf6',
    'rpl'     : '#06b6d4',
    'random'  : '#ef4444',
}

os.makedirs('figures', exist_ok=True)


def style_ax(ax):
    """Apply consistent dark theme to all axes."""
    ax.set_facecolor(SURFACE)
    ax.tick_params(colors=SOFT, labelsize=9)
    ax.xaxis.label.set_color(SOFT)
    ax.yaxis.label.set_color(SOFT)
    ax.title.set_color(TEXT)
    for spine in ax.spines.values():
        spine.set_color(BORDER)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.grid(axis='y', color=BORDER, alpha=0.5, zorder=0)


# ═══════════════════════════════════════════════════
#  FIGURE 1: Protocol Comparison (3-panel)
# ═══════════════════════════════════════════════════
def plot_protocol_comparison():
    """
    WHY THIS FIGURE:
    This is the main result figure of the paper.
    Three panels side by side:
      Panel A — PDR (%) : higher is better
      Panel B — Mean Reroute Time : lower is better
      Panel C — False Reroute Rate : lower is better

    ATRP should be best or competitive on all three.
    RPL edges ATRP on PDR — we show this honestly.
    ATRP clearly wins on reroute time and false reroute rate.
    """
    with open('results/experiment1_protocol_comparison.json') as f:
        data = json.load(f)

    labels   = [r['label']           for r in data]
    pdrs     = [r['pdr']             for r in data]
    reroutes = [min(r['mean_reroute'], 50) for r in data]  # cap at 50 for visibility
    frrs     = [r['false_reroute_pct'] for r in data]
    protos   = [r['protocol']        for r in data]
    colors   = [COLORS.get(p, '#64748b') for p in protos]

    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    fig.patch.set_facecolor(BG)
    fig.suptitle(
        'ATRP vs Baseline Protocols — 50-node IoT Network, 1000 Ticks',
        color=TEXT, fontsize=13, y=1.02
    )

    # Panel A: PDR
    ax = axes[0]
    style_ax(ax)
    bars = ax.bar(labels, pdrs, color=colors, width=0.6, zorder=3)
    bars[0].set_edgecolor('#93c5fd')
    bars[0].set_linewidth(2)
    ax.set_title('(A) Packet Delivery Rate', fontsize=11, pad=10)
    ax.set_ylabel('PDR (%)', fontsize=10)
    ax.set_ylim(0, max(pdrs) * 1.2)
    for bar, val in zip(bars, pdrs):
        ax.text(bar.get_x() + bar.get_width()/2,
                bar.get_height() + 0.3,
                f'{val}%', ha='center', va='bottom',
                color=TEXT, fontsize=9, fontweight='bold')
    ax.set_xticklabels(labels, rotation=25, ha='right')

    # Panel B: Reroute Time (capped)
    ax = axes[1]
    style_ax(ax)
    bars2 = ax.bar(labels, reroutes, color=colors, width=0.6, zorder=3)
    bars2[0].set_edgecolor('#93c5fd')
    bars2[0].set_linewidth(2)
    ax.set_title('(B) Mean Reroute Time (ticks)\n[Dijkstra capped at 50]',
                 fontsize=11, pad=10)
    ax.set_ylabel('Ticks', fontsize=10)
    for bar, val, orig in zip(bars2, reroutes,
                               [r['mean_reroute'] for r in data]):
        label = f'{orig}' if orig <= 50 else f'{orig:.0f}*'
        ax.text(bar.get_x() + bar.get_width()/2,
                bar.get_height() + 0.3,
                label, ha='center', va='bottom',
                color=TEXT, fontsize=9, fontweight='bold')
    ax.set_xticklabels(labels, rotation=25, ha='right')

    # Panel C: False Reroute Rate
    ax = axes[2]
    style_ax(ax)
    bars3 = ax.bar(labels, frrs, color=colors, width=0.6, zorder=3)
    bars3[0].set_edgecolor('#93c5fd')
    bars3[0].set_linewidth(2)
    ax.set_title('(C) False Reroute Rate (%)\n[Lower = better]',
                 fontsize=11, pad=10)
    ax.set_ylabel('False Reroute (%)', fontsize=10)
    for bar, val in zip(bars3, frrs):
        ax.text(bar.get_x() + bar.get_width()/2,
                bar.get_height() + 0.3,
                f'{val}%', ha='center', va='bottom',
                color=TEXT, fontsize=9, fontweight='bold')
    ax.set_xticklabels(labels, rotation=25, ha='right')

    plt.tight_layout()
    path = 'figures/02_protocol_comparison.png'
    plt.savefig(path, dpi=150, bbox_inches='tight',
                facecolor=BG, edgecolor='none')
    plt.close()
    print(f'  Saved -> {path}')


# ═══════════════════════════════════════════════════
#  FIGURE 2: Lambda Grid Search
# ═══════════════════════════════════════════════════
def plot_lambda_search():
    """
    WHY THIS FIGURE:
    Shows PDR as a function of lambda (0.0 to 1.0).
    Proves lambda=0.7 is the empirically optimal value.
    The curve shape shows the explore-exploit tradeoff —
    pure trust routing (lambda=0) and pure distance
    routing (lambda=1) both underperform the balanced value.
    """
    with open('results/experiment2_lambda_search.json') as f:
        data = json.load(f)

    lambdas  = data['lambdas']
    pdr_vals = data['pdr_vals']
    optimal  = data['optimal']
    best_pdr = data['best_pdr']

    fig, ax = plt.subplots(figsize=(9, 5))
    fig.patch.set_facecolor(BG)
    style_ax(ax)

    ax.plot(lambdas, pdr_vals,
            color=COLORS['atrp'], lw=2.5,
            marker='o', markersize=7,
            markerfacecolor=BG, markeredgecolor=COLORS['atrp'],
            markeredgewidth=2, zorder=3)

    # Highlight optimal point
    opt_idx = lambdas.index(optimal)
    ax.scatter([optimal], [best_pdr],
               color='#10b981', s=120, zorder=5)
    ax.axvline(x=optimal, color='#10b981',
               lw=1.5, ls='--', alpha=0.7)
    ax.annotate(
        f'Optimal λ={optimal}\nPDR={best_pdr}%',
        xy=(optimal, best_pdr),
        xytext=(optimal + 0.08, best_pdr - 3),
        color='#10b981', fontsize=10,
        arrowprops=dict(arrowstyle='->', color='#10b981', lw=1.5)
    )

    # Shade regions
    ax.axvspan(0, 0.35, alpha=0.04, color='#ef4444',
               label='Trust-dominant zone')
    ax.axvspan(0.35, 0.75, alpha=0.04, color='#10b981',
               label='Balanced zone')
    ax.axvspan(0.75, 1.0, alpha=0.04, color='#f59e0b',
               label='Distance-dominant zone')

    ax.set_title('Lambda Grid Search — Explore-Exploit Parameter Tuning',
                 fontsize=12, pad=12)
    ax.set_xlabel('Lambda (λ)', fontsize=11)
    ax.set_ylabel('Packet Delivery Rate (%)', fontsize=11)
    ax.set_xticks(lambdas)
    ax.legend(facecolor=SURFACE, edgecolor=BORDER,
              labelcolor=SOFT, fontsize=9)

    plt.tight_layout()
    path = 'figures/03_lambda_grid_search.png'
    plt.savefig(path, dpi=150, bbox_inches='tight',
                facecolor=BG, edgecolor='none')
    plt.close()
    print(f'  Saved -> {path}')


# ═══════════════════════════════════════════════════
#  FIGURE 3: Weight Sensitivity Analysis
# ═══════════════════════════════════════════════════
def plot_weight_sensitivity():
    """
    WHY THIS FIGURE:
    Shows PDR for 6 different TW weight configurations
    averaged across 5 random seeds.
    Proves that the empirically validated weights
    (uptime-heavy w1=0.50) outperform alternatives.
    Converts our weight choice from assumption to evidence.
    """
    with open('results/experiment3b_multirun.json') as f:
        data = json.load(f)

    labels   = [d['label']   for d in data]
    avg_pdrs = [d['avg_pdr'] for d in data]
    stds     = [d['std']     for d in data]

    bar_colors = ['#10b981' if d['weights'] == [0.50, 0.20, 0.20, 0.10]
                  else COLORS['atrp'] if d['label'] == 'Default'
                  else '#64748b'
                  for d in data]

    fig, ax = plt.subplots(figsize=(10, 5))
    fig.patch.set_facecolor(BG)
    style_ax(ax)

    bars = ax.bar(labels, avg_pdrs, color=bar_colors,
                  width=0.6, zorder=3,
                  yerr=stds, capsize=5,
                  error_kw={'ecolor': SOFT, 'elinewidth': 1.5})

    ax.set_title(
        'Weight Sensitivity Analysis — TW Formula Validation\n'
        '(Average PDR across 5 random seeds ± std)',
        fontsize=12, pad=12
    )
    ax.set_ylabel('Average PDR (%)', fontsize=11)
    ax.set_ylim(0, max(avg_pdrs) * 1.25)

    for bar, val, std in zip(bars, avg_pdrs, stds):
        ax.text(bar.get_x() + bar.get_width()/2,
                bar.get_height() + std + 0.5,
                f'{val}%', ha='center', va='bottom',
                color=TEXT, fontsize=9, fontweight='bold')

    ax.set_xticklabels(labels, rotation=20, ha='right')

    legend_handles = [
        mpatches.Patch(color='#10b981', label='Empirical winner (Uptime-heavy)'),
        mpatches.Patch(color=COLORS['atrp'], label='Original default weights'),
        mpatches.Patch(color='#64748b', label='Other configurations'),
    ]
    ax.legend(handles=legend_handles, facecolor=SURFACE,
              edgecolor=BORDER, labelcolor=SOFT, fontsize=9)

    plt.tight_layout()
    path = 'figures/04_weight_sensitivity.png'
    plt.savefig(path, dpi=150, bbox_inches='tight',
                facecolor=BG, edgecolor='none')
    plt.close()
    print(f'  Saved -> {path}')


# ═══════════════════════════════════════════════════
#  FIGURE 4: TW Distribution Snapshot
# ═══════════════════════════════════════════════════
def plot_tw_distribution():
    """
    WHY THIS FIGURE:
    Shows the distribution of TW scores across all 50 nodes
    after the simulation runs.
    Coloured by zone: Avoid / Monitor / Trusted.
    Gives reviewers a visual of how ATRP classifies nodes
    and how many fall in each reliability zone.
    """
    import random
    import sys
    sys.path.insert(0, 'src')
    from graph import build_iot_graph
    from trust import tw_initialise, tw_update, ZONE_AVOID, ZONE_TRUSTED

    random.seed(42)
    G     = build_iot_graph()
    nodes = list(G.nodes())
    tw, uptime, failures, tx_count, lat_sum, battery, total_t = tw_initialise(nodes)
    failed_nodes = set()

    # Run 200 ticks to get realistic TW distribution
    for tick in range(200):
        for n in nodes:
            roll = random.random()
            if n in failed_nodes:
                event = 'recover' if roll < 0.06 else 'silent'
                if event == 'recover':
                    failed_nodes.discard(n)
            elif roll < 0.02:
                event = 'failure'
                failed_nodes.add(n)
            else:
                event = 'observe'
            tw_update(n, event, tw, uptime, failures,
                      tx_count, lat_sum, battery, total_t, dt=1)

    tw_vals = list(tw.values())
    avoid   = [v for v in tw_vals if v < ZONE_AVOID]
    monitor = [v for v in tw_vals if ZONE_AVOID <= v < ZONE_TRUSTED]
    trusted = [v for v in tw_vals if v >= ZONE_TRUSTED]

    fig, ax = plt.subplots(figsize=(9, 5))
    fig.patch.set_facecolor(BG)
    style_ax(ax)
    ax.grid(axis='x', color=BORDER, alpha=0.5)
    ax.grid(axis='y', color=BORDER, alpha=0.3)

    ax.hist(avoid,   bins=8, color='#ef4444',
            alpha=0.85, label=f'Avoid zone (<0.4) — {len(avoid)} nodes',
            zorder=3)
    ax.hist(monitor, bins=8, color='#f59e0b',
            alpha=0.85, label=f'Monitor zone (0.4-0.7) — {len(monitor)} nodes',
            zorder=3)
    ax.hist(trusted, bins=8, color='#10b981',
            alpha=0.85, label=f'Trusted zone (>0.7) — {len(trusted)} nodes',
            zorder=3)

    ax.axvline(x=ZONE_AVOID,   color='#ef4444',
               lw=1.5, ls='--', alpha=0.6)
    ax.axvline(x=ZONE_TRUSTED, color='#10b981',
               lw=1.5, ls='--', alpha=0.6)

    ax.set_title(
        'Trust Weight Distribution — 50 Nodes after 200 Simulation Ticks',
        fontsize=12, pad=12
    )
    ax.set_xlabel('Trust Weight (TW)', fontsize=11)
    ax.set_ylabel('Number of Nodes', fontsize=11)
    ax.legend(facecolor=SURFACE, edgecolor=BORDER,
              labelcolor=SOFT, fontsize=9)

    plt.tight_layout()
    path = 'figures/05_tw_distribution.png'
    plt.savefig(path, dpi=150, bbox_inches='tight',
                facecolor=BG, edgecolor='none')
    plt.close()
    print(f'  Saved -> {path}')


if __name__ == '__main__':
    print("\n" + "="*60)
    print("  ATRP — Generating Paper Figures")
    print("="*60)

    print("\n  Figure 1: Protocol Comparison...")
    plot_protocol_comparison()

    print("  Figure 2: Lambda Grid Search...")
    plot_lambda_search()

    print("  Figure 3: Weight Sensitivity...")
    plot_weight_sensitivity()

    print("  Figure 4: TW Distribution...")
    plot_tw_distribution()

    print("\n  All figures saved to figures/")
    print("  plots.py -- DONE\n")